### ISSUE TITLE
Honor superclass in result objects

### ISSUE THREAD

**Issue by starlys** [dart-lang/rpc#90] opened 2016-04-14 23:36 UTC
It would be helpful to have API methods like this:
* CustomerInfo getCustomer(...)
* VendorInfo getVendor(...)

where CustomerInfo and VendorInfo both derive from BaseInfo. 

Currently if BaseInfo declares some properties, and the API method sets them and returns an instance of VendorInfo, those properties will be ignored. Only the properties declared directly in VendorInfo are serialized into the response.

**Comment by seanmccleary** [comment] 2016-09-12 22:26
I agree that this would be very useful.  Especially considering that many applications may have model classes with common attributes, such as "id" and "createdAt" and "updatedAt", etc.  Being able to house these in a superclass (or mixin class) would be much nicer than repeating them on every class.

I've created a branch that does just this.  I haven't tested it.  Check it out at your own peril:

https://github.com/seanmccleary/rpc/tree/inherited-class-members

It was actually only a three-line change:

https://github.com/dart-lang/rpc/compare/master...seanmccleary:inherited-class-members

I'd like to see this make its way into the official codebase somehow.  (Though at this point, I don't know how they could without it breaking the current, expected behavior.)

**Comment by mkustermann** [comment] 2016-10-10 13:13
@seanmccleary Provided and opt-in solution vi:
```
@ApiMessage(includeSuper: true)
class MessageClass extends BaseMessageClass {
  ...
}
```

So I'll go ahead and close this issue.

Though it might make sense to note here, that this is not the same as real polymorphism. Meaning that if an api method is declared as `Future<Info> getInfo()` it cannot return subclasses of `Info` AFAIK.

**Closed by mkustermann** 2016-10-10 13:13 UTC

**Comment by jodinathan** [comment] 2016-10-14 18:29
I guess this is not the very best solution, since models can be in another library (mine are).
I will have to import the rpc package in my model project just for that.

**Comment by seanmccleary** [comment] 2016-10-14 18:52
@jodinathan this is true.  I considered that also, but given that the @ApiProperty annotation has already set the precedent, I didn't sweat it.

**Comment by jodinathan** [comment] 2016-10-14 19:01
@seanmccleary, in my case, the @ApiProperty aren't that useful because my models need more complex validations, like "the document_id is required if the birthday is greater than 1998" for example. 
So I will have an internal validation system, which will be used at the server level and also the frontend level, since we will use Dart at both sides.
But got your point, no need to stress about it I guess.

thanks for the very fast response.
